### ISSUE TITLE
Preview without save requirement

### ISSUE THREAD

**Issue by ItsJayPM** [GoAnimate-Wrapper/GoAnimate-Wrapper#19]
I'm working on getting the previews that other Vyond clones have (as in you don't need to save them)

I'm just adding this here to help keep everyone watching the project informed.
It might take a while, but I know it is absolutely possible.

**Comment by ItsJayPM** [comment]
Completed the first half of my project. I have tracked down all _(or at least most of)_ the functions. Hopefully I can get it done within **this week**.

**Comment by Windows81** [comment]
The problem in this case is not versionisation, but rather of how the data is transferred.  As you know, the player has an ext-preview mode which receives XML-like data from the LVM itself.  The problem is that this could span **many megabytes**.  I wanted the preview window to show up separate to the LVM in the first place.

In the past, I sent all the data to the server then had the preview window _suck it all out_.  That didn't work very well because EvenNode has maximum size quotas for sending data to the server.  I also couldn't send in batch because that would kinda halt the server too.  I also tried storing it in local caché, but to no avail.

That's why I'm closing this issue.
